In [9]:
import numpy as np
import pandas as pd

# data load
df_op21 = pd.read_excel('C:/Users/onebe/태림산업 설비데이터(24.01.01~24.05.14)/op20-1.xlsx')
df_op31 = pd.read_excel('C:/Users/onebe/태림산업 설비데이터(24.01.01~24.05.14)/op30-1.xlsx')
df_op40T = pd.read_excel('C:/Users/onebe/태림산업 설비데이터(24.01.01~24.05.14)/op40T.xlsx')

In [10]:
df_op21

,번호,시각,차종,차종번호,작업자,바코드1,바코드2,바코드3,바코드4,판정,...,우1차피크,우옵셋하한,우옵셋상한,우옵셋하중,우완료하중하한,우완료하중상한,우완료하중,우완료거리하한,우완료거리상한,우완료거리
0,1,2024-01-02 오전 8:36:10,MQB27-RHD,1,김미옥,A021N566RA 259213 T0144B 231219,03106 A2306002 B 231201 02160,01414 A2304025 O 231201 00080,03106 A2306001 C 231201 00300,합격,...,405.793,0,20,0,100,500,0,10.0,13.0,10.18
1,2,2024-01-02 오전 8:37:15,MQB27-RHD,1,김미옥,A021N566RA 259213 T0014A 231220,03106 A2306002 B 231201 02160,01414 A2304025 O 231201 00080,03106 A2306001 C 231201 00300,합격,...,406.976,0,20,0,100,500,0,10.0,13.0,10.18
2,3,2024-01-02 오전 8:38:46,MQB27-RHD,1,김미옥,A021N566RA 259213 T0020A 231220,03106 A2306002 B 231201 02160,01414 A2304025 O 231201 00080,03106 A2306001 C 231201 00300,합격,...,449.471,0,20,0,100,500,0,10.0,13.0,10.18
3,4,2024-01-02 오전 8:39:21,MQB27-RHD,1,김미옥,A021N566RA 259213 T0018A 231220,03106 A2306002 B 231201 02160,01414 A2304025 O 231201 00080,03106 A2306001 C 231201 00300,합격,...,386.074,0,20,0,100,500,0,10.0,13.0,10.18
4,5,2024-01-02 오전 8:39:57,MQB27-RHD,1,김미옥,A021N566RA 259213 T0023A 231220,03106 A2306002 B 231201 02160,01414 A2304025 O 231201 00080,03106 A2306001 C 231201 00300,합격,...,386.666,0,20,0,100,500,0,10.0,13.0,10.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202341,500,2024-05-14 오후 12:17:57,MQB27-LHD,1,김현애,A021N565RB 259213 T1051A 240507,03106 A2306002 B 240401 02160,01414 A2304025 O 240501 00080,03106 A2306001 C 240501 00300,합격,...,307.986,0,20,0,100,500,0,9.5,11.5,10.18
202342,501,2024-05-14 오후 12:18:20,MQB27-LHD,1,김현애,A021N565RB 259213 T1056A 240507,03106 A2306002 B 240401 02160,01414 A2304025 O 240501 00080,03106 A2306001 C 240501 00300,합격,...,357.383,0,20,0,100,500,0,9.5,11.5,10.18
202343,502,2024-05-14 오후 12:18:42,MQB27-LHD,1,김현애,A021N565RB 259213 T1040A 240507,03106 A2306002 B 240401 02160,01414 A2304025 O 240501 00080,03106 A2306001 C 240501 00300,합격,...,367.637,0,20,0,100,500,0,9.5,11.5,10.18
202344,503,2024-05-14 오후 12:19:04,MQB27-LHD,1,김현애,A021N565RB 259213 T6124A 240507,03106 A2306002 B 240401 02160,01414 A2304025 O 240501 00080,03106 A2306001 C 240501 00300,합격,...,360.242,0,20,0,100,500,0,9.5,11.5,10.18
202345,504,2024-05-14 오후 12:19:34,MQB27-LHD,1,김현애,A021N565RB 259213 T6119A 240507,03106 A2306002 B 240401 02160,01414 A2304025 O 240501 00080,03106 A2306001 C 240501 00300,합격,...,329.283,0,20,0,100,500,0,9.5,11.5,10.18

In [11]:
# column edit
df_op21 = df_op21.drop('번호', axis=1)
df_op21 = df_op21.drop('시각', axis=1)
df_op21 = df_op21.drop('차종', axis=1)
df_op21 = df_op21.drop('차종번호', axis=1)
df_op21 = df_op21.drop('작업자', axis=1)
df_op21 = df_op21.drop('바코드2', axis=1)
df_op21 = df_op21.drop('바코드3', axis=1)
df_op21 = df_op21.drop('바코드4', axis=1)

df_op31 = df_op31.drop('번호', axis=1)
df_op31 = df_op31.drop('시각', axis=1)
df_op31 = df_op31.drop('차종', axis=1)
df_op31 = df_op31.drop('차종번호', axis=1)
df_op31 = df_op31.drop('작업자', axis=1)
df_op31 = df_op31.drop('바코드2', axis=1)
df_op31 = df_op31.drop('바코드3', axis=1)
df_op31 = df_op31.drop('바코드4', axis=1)

df_op40T = df_op40T.drop('번호', axis=1)
df_op40T = df_op40T.drop('시각', axis=1)
df_op40T = df_op40T.drop('차종', axis=1)
df_op40T = df_op40T.drop('차종번호', axis=1)
df_op40T = df_op40T.drop('작업자', axis=1)

In [12]:
df_op21['판정'] = df_op21['판정'].map({'합격': 1, '불합격': 0})
df_op31['판정'] = df_op31['판정'].map({'합격': 1, '불합격': 0})

df_op40T['판정'] = df_op40T['판정'].map({'합격': 1, '불합격': 0})
df_op40T['비젼합부'] = df_op40T['비젼합부'].map({'OK': 1, 'NG': 0})
df_op40T['TTA1합부'] = df_op40T['TTA1합부'].map({'OK': 1, 'NG': 0})
df_op40T['TTA2합부'] = df_op40T['TTA2합부'].map({'OK': 1, 'NG': 0})
df_op40T['씰검사합부'] = df_op40T['씰검사합부'].map({'OK': 1, 'NG': 0})
df_op40T['탭검사합부'] = df_op40T['탭검사합부'].map({'OK': 1, 'NG': 0})

In [13]:
# missing barcode eliminate
df_op21 = df_op21.dropna(axis=0)
df_op31 = df_op31.dropna(axis=0)
df_op40T = df_op40T.dropna(axis=0)

#%% Data Integration

df_op21 = df_op21.add_prefix('OP21')
df_op31 = df_op31.add_prefix('OP31')

df_op40T = df_op40T.add_prefix('OP40T')

# Barcode presentation Standarize
df_op21.rename(columns = {'OP21바코드1': '튜브바코드'}, inplace=True)
df_op31.rename(columns = {'OP31바코드1': '튜브바코드'}, inplace=True)
df_op40T.rename(columns = {'OP40T바코드': '튜브바코드'}, inplace=True)

In [1]:
# OP Data Integration
df_op2140T = pd.merge(left=df_op21, right=df_op31, how="right", on="튜브바코드")
df_op2140T = df_op2140T.dropna(axis=0)
df_op2140T = pd.merge(left=df_op2140T , right=df_op40S, how="right", on="튜브바코드")
df_op2140T = df_op2140T.dropna(axis=0)

In [ ]:
df_op20

In [15]:
df_op2040S

,샤프트바코드,OP20판정,OP20전장하한,OP20전장상한,OP20전장,OP20거리하한,OP20거리상한,OP20거리,OP20캡간하한,OP20캡간상한,...,OP40STTA1CCW최소,OP40STTA1CCW최대,OP40STTA2합부,OP40STTA2CW최소,OP40STTA2CW최대,OP40STTA2CCW최소,OP40STTA2CCW최대,OP40S씰검사합부,OP40S탭검사합부,OP40S전류최대
3,A021N566RA 259213 S6562A 231221,1.0,-125.0,125.0,114.943,-0.15,0.15,-0.049,38.4,39.0,...,0.030,0.040,1,0.068,0.088,0.047,0.077,1,1,0.606
4,A021N566RA 259213 S6615A 231221,1.0,-125.0,125.0,114.840,-0.15,0.15,-0.024,38.4,39.0,...,0.059,0.090,1,0.048,0.077,0.037,0.057,1,1,0.601
5,A021N566RA 259213 S6605A 231221,1.0,-125.0,125.0,114.635,-0.15,0.15,-0.032,38.4,39.0,...,0.070,0.100,1,0.058,0.102,0.047,0.067,1,1,0.599
6,A021N566RA 259213 S6603A 231221,1.0,-125.0,125.0,115.148,-0.15,0.15,-0.022,38.4,39.0,...,0.049,0.059,1,0.048,0.068,0.027,0.047,1,1,0.595
7,A021N566RA 259213 S6602A 231221,1.0,-125.0,125.0,114.943,-0.15,0.15,-0.043,38.4,39.0,...,0.031,0.050,1,0.048,0.078,0.047,0.067,1,1,0.592
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201511,A021N565RB 259213 S5882B 240430,1.0,-125.0,125.0,117.611,-0.15,0.15,-0.050,38.4,39.0,...,0.067,0.088,1,0.003,0.047,0.007,0.037,1,1,0.549
201512,A021N565RB 259213 S5726B 240430,1.0,-125.0,125.0,117.098,-0.15,0.15,-0.050,38.4,39.0,...,0.088,0.098,1,0.003,0.039,0.007,0.027,1,1,0.551
201513,A021N565RB 259213 S5763B 240430,1.0,-125.0,125.0,116.892,-0.15,0.15,-0.050,38.4,39.0,...,0.077,0.108,1,0.003,0.039,0.007,0.037,1,1,0.550
201514,A021N565RB 259213 S6036B 240430,1.0,-125.0,125.0,117.200,-0.15,0.15,-0.050,38.4,39.0,...,0.118,0.138,1,0.030,0.039,0.030,0.037,1,1,0.550
201515,A021N565RB 259213 S5986B 240430,1.0,-125.0,125.0,117.098,-0.15,0.15,-0.050,38.4,39.0,...,0.121,0.148,1,0.003,0.072,0.029,0.037,1,1,0.549

In [16]:
df_op2040S.to_csv('C:/Users/onebe/태림산업 설비데이터(24.01.01~24.05.14)/df_2140.csv', index=False, encoding='UTF-8')

In [ ]:
df = pd.read_csv('df_2040.csv', encoding='UTF-8')


print(df.head())
print('------------')
print(df.shape)

In [ ]:
#독립변수선정
df2 = df[['OP20판정','OP20전장','OP20거리','OP20캡간','OP20좌1차피크','OP20좌완료거리','OP20우1차피크','OP20우완료거리하한',
          'OP20우완료거리','OP30판정','OP30전장','OP30거리','OP30캡간','OP30좌1차피크','OP30좌완료거리','OP30우1차피크',
          'OP30우완료거리','OP40S베어링거리','OP40S베어링쏠림량','OP40S스태킹깊이최소','OP40S스태킹깊이최대',
          'OP40S스태킹가로폭최소','OP40S스태킹가로폭최대','OP40S스태킹세로폭최소','OP40S스태킹세로폭최대','OP40S스태킹형상최소',
          'OP40S스태킹형상최대','OP40SB베어링거리','OP40SB베어링쏠림량','OP40SB스태킹깊이최소','OP40SB스태킹깊이최대',
          'OP40SB스태킹가로폭최소','OP40SB스태킹가로폭최대','OP40SB스태킹세로폭최소','OP40SB스태킹세로폭최대','OP40SB스태킹형상최소',
          'OP40SB스태킹형상최대','OP40S요크깊이편차','OP40SC요크깊이편차','OP40STTA1CW최소','OP40STTA1CW최대','OP40STTA1CCW최소',
          'OP40STTA1CCW최대','OP40STTA2CW최소','OP40STTA2CW최대','OP40STTA2CCW최소','OP40STTA2CCW최대','OP40S전류최대']]

df2

In [ ]:

print(df2.head())
print('------------')
print(df2.shape)

In [ ]:
#df2040 =  pd.read_csv('C:/Users/onebe/taelim_Regression/df_2040.csv', encoding='UTF-8')
df2040

In [ ]:
df2140 =  pd.read_csv('C:/Users/onebe/taelim_Regression/df_2140T.csv', encoding='UTF-8')

df2140

In [ ]:
df_all = pd.merge(left=df_op2040S , right=df_op40S, how="right", on="샤프트바코드")
df_op2040S = df_op2040S.dropna(axis=0)

In [ ]:
import numpy as np
import pandas as pd


df = pd.read_csv('C:/Users/onebe/태림산업 설비데이터(24.01.01~24.05.14)/df_2040.csv', encoding='UTF-8')
df = pd.read_csv('C:/Users/onebe/태림산업 설비데이터(24.01.01~24.05.14)/df_2040.csv', encoding='UTF-8')
df = pd.read_csv('C:/Users/onebe/태림산업 설비데이터(24.01.01~24.05.14)/df_2040.csv', encoding='UTF-8')